[package]
name = "fs-fuse"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
fs-demo = { path = "../fs-demo" }
rand = "0.8.0"